server {
        server_name URL.com; ##add url
        location / {
                proxy_set_header  Host $host;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-Proto https;
                proxy_set_header  X-Forwarded-For $remote_addr;
                proxy_set_header  X-Forwarded-Host $remote_addr;
                proxy_pass http://localhost:8087/; ##add port
        }
}

server {
    server_name URL.com; ##add URL
    listen 80;
}